# Generated by Django 4.2.1 on 2023-05-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_auth', '0003_recentusedmenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentusedmenu',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='recentusedmenu',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='recentusedmenu',
            old_name='user_id',
            new_name='user',
        ),
    ]
