# Generated by Django 4.2.1 on 2023-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_syslog_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syslog',
            name='url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
